# Generated by Django 4.2.5 on 2023-09-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("id_premium", models.BooleanField(null=True)),
                ("promotion_end_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
