# Generated by Django 4.2.5 on 2023-09-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee", name="description", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="coffee",
            name="specical_price",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
