# Generated by Django 4.2.2 on 2023-09-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0002_coffee_description_coffee_specical_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffee", name="description",),
    ]
