# Generated by Django 4.2.2 on 2023-09-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0004_coffee_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffee", old_name="id_premium", new_name="is_premium",
        ),
    ]
