# Generated by Django 4.2.2 on 2023-09-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0005_rename_id_premium_coffee_is_premium"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffee", old_name="specical_price", new_name="special_price",
        ),
    ]
