# Generated by Django 4.2.2 on 2023-09-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0007_alter_coffee_special_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffee", old_name="special_price", new_name="special_price_new",
        ),
    ]
