# Generated by Django 4.2.2 on 2023-09-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0008_rename_special_price_coffee_special_price_new"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffee", old_name="special_price_new", new_name="special_price",
        ),
    ]
