# Generated by Django 4.2.2 on 2023-09-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0009_rename_special_price_new_coffee_special_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffee", name="special_price",),
    ]
