# Generated by Django 4.2.2 on 2023-09-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0010_remove_coffee_special_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="special_price",
            field=models.IntegerField(null=True),
        ),
    ]
