# Generated by Django 4.2.2 on 2023-09-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0011_coffee_special_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="special_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
