# Generated by Django 4.2.2 on 2023-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cof", "0013_alter_coffee_special_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="image",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="coffee",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coffee",
            name="promotion_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coffee",
            name="special_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
