# Generated by Django 4.2.2 on 2023-09-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registerd_at", models.DateTimeField(auto_created=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unapproved", "Unapproved"),
                            ("approved", "Approved"),
                            ("banned", "Banned"),
                        ],
                        default="unapproved",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
